/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp dbus/xyz.freedom.v2ray.xml -i src/jolla-settings-v2ray.h -a src/adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ADAPTOR_H
#define ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "src/jolla-settings-v2ray.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface xyz.freedom.v2ray
 */
class V2rayAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "xyz.freedom.v2ray")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"xyz.freedom.v2ray\">\n"
"    <method name=\"doProxy\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"fname\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"ok\"/>\n"
"    </method>\n"
"    <signal name=\"statusChanged\">\n"
"      <arg type=\"s\" name=\"fname\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    V2rayAdaptor(QObject *parent);
    virtual ~V2rayAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool doProxy(const QString &fname);
Q_SIGNALS: // SIGNALS
    void statusChanged(const QString &fname);
};

#endif
